version: '3'
services:
    dev-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: [ "scrapyd", "--pidfile=" ]
        networks:
            - dev-network
        ports:
            - "8060:8060"
        restart: 'on-failure'
        volumes:
            # Update this to wherever you want VS Code to mount the folder of your project
            - .:/workspace
            # Forwards the local Docker socket to the container.
            - /var/run/docker.sock:/var/run/docker.sock
            # persist log and data to volumes between docker runs
            - scrapyd-log:/var/log/scrapyd
            - scrapyd-data:/var/lib/scrapyd
            # mount external scrapyd configuration
            - ./config/scrapyd.conf:/etc/scrapyd/scrapyd.conf

    splash:
        container_name: scrapy-server-splash
        image: scrapinghub/splash
        networks:
            - dev-network
        ports:
            - "8050:8050"
        restart: 'on-failure'

volumes:
    scrapyd-log:
    scrapyd-data:

networks:
    dev-network:
        driver: bridge
